[package]
name = "lockr-cli"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
secrecy = "0.8"
serde_json = "1.0"
lockr-core = { path = "../core" }
